---
services:
  minio:
    image: bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio#password
      - MINIO_DEFAULT_BUCKETS=airflow-logs
    volumes:
      - minio_data:/bitnami/minio/data
    networks:
      - minio_network

  mailhog:
    image: mailhog/mailhog
    networks:
      - minio_network
    ports:
      - '1025:1025'
      - '8025:8025'

networks:
  minio_network:
    name: airflow
    driver: bridge

volumes:
  minio_data:
#    driver: local
